---
services:

  ## trusted-policies-registry-api-v2 (trusted-policies-registry-api-v2)
#  trusted-policies-registry-api-v2:
#    image: ${IMAGE_NAME_trusted_policies_registry_api_v2}:${IMAGE_TAG_trusted_policies_registry_api_v2:-local}
#    extends:
#      file: ./common.yaml
#      service: common-core-service-api
#    build:
#      context: "${GIT_CORE_SERVICES}/apis/trusted-policies-registry"
#    env_file:
#      - path: ${ENV_DIR_CORE_SERVICES}/all_nodes/common.env
#        required: false
#      - path: ${ENV_DIR_CORE_SERVICES}/all_nodes/core-services/common.env
#        required: false
#      - path: ${ENV_DIR_CORE_SERVICES}/all_nodes/core-services/trusted-policies-registry-api-v2.env
#        required: false
#    labels:
#      - traefik.enable=true
#      - traefik.http.routers.trusted-policies-registry-api-v2.rule=Host(`${API_DOMAIN}`)&&PathPrefix(`/trusted-policies-registry/v2`)
#      - traefik.http.routers.trusted-policies-registry-api-v2.service=trusted-policies-registry-api-v2
#      - traefik.http.routers.trusted-policies-registry-api-v2.entrypoints=web,web-secure
#      - traefik.http.middlewares.trusted-policies-registry-api-v2-headers.headers.stspreload=true
#      - traefik.http.middlewares.trusted-policies-registry-api-v2-headers.headers.stsseconds=31536000
#      - traefik.http.middlewares.trusted-policies-registry-api-v2-headers.headers.contenttypenosniff=true
#      - traefik.http.middlewares.trusted-policies-registry-api-v2-headers.headers.referrerpolicy=origin-when-cross-origin
#      - traefik.http.routers.trusted-policies-registry-api-v2.middlewares=trusted-policies-registry-api-v2-headers@docker
#      - traefik.http.services.trusted-policies-registry-api-v2.loadbalancer.server.port=3000
#      - traefik.http.services.trusted-policies-registry-api-v2.loadbalancer.healthcheck.path=/trusted-policies-registry/v2/health
#      - traefik.http.services.trusted-policies-registry-api-v2.loadbalancer.healthcheck.headers.EBSI-Healthcheck=1
#      - traefik.http.services.trusted-policies-registry-api-v2.loadbalancer.healthcheck.interval=30s
#      - traefik.http.services.trusted-policies-registry-api-v2.loadbalancer.healthcheck.timeout=30s
#      - traefik.http.routers.local-trusted-policies-registry-api-v2.rule=Host(`api.local`)&&PathPrefix(`/trusted-policies-registry/v2`)
#      - traefik.http.routers.local-trusted-policies-registry-api-v2.service=local-trusted-policies-registry-api-v2
#      - traefik.http.services.local-trusted-policies-registry-api-v2.loadbalancer.server.port=3000
#      - app=trusted-policies-registry-api-v2

  ## trusted-policies-registry-api-v3 (trusted-policies-registry-api-v3)
  trusted-policies-registry-api-v3:
    image: ${IMAGE_NAME_trusted_policies_registry_api_v3}:${IMAGE_TAG_trusted_policies_registry_api_v3:-local}
    extends:
      file: ./common.yaml
      service: common-core-service-api
    build:
      context: "${GIT_CORE_SERVICES}/apis/trusted-policies-registry-v3"
    env_file:
      - path: ${ENV_DIR_CORE_SERVICES}/all_nodes/common.env
        required: false
      - path: ${ENV_DIR_CORE_SERVICES}/all_nodes/core-services/common.env
        required: false
      - path: ${ENV_DIR_CORE_SERVICES}/all_nodes/core-services/trusted-policies-registry-api-v3.env
        required: false
    labels:
      - traefik.enable=true
      - traefik.http.routers.trusted-policies-registry-api-v3.rule=Host(`${API_DOMAIN}`)&&PathPrefix(`/trusted-policies-registry/v3`)
      - traefik.http.routers.trusted-policies-registry-api-v3.service=trusted-policies-registry-api-v3
      - traefik.http.routers.trusted-policies-registry-api-v3.entrypoints=web,web-secure
      - traefik.http.routers.trusted-policies-registry-api-v3.tls=true
      - traefik.http.routers.trusted-policies-registry-api-v3.tls.certresolver=letsencrypt-tls
      - traefik.http.middlewares.trusted-policies-registry-api-v3-headers.headers.stspreload=true
      - traefik.http.middlewares.trusted-policies-registry-api-v3-headers.headers.stsseconds=31536000
      - traefik.http.middlewares.trusted-policies-registry-api-v3-headers.headers.contenttypenosniff=true
      - traefik.http.middlewares.trusted-policies-registry-api-v3-headers.headers.referrerpolicy=origin-when-cross-origin
      - traefik.http.routers.trusted-policies-registry-api-v3.middlewares=trusted-policies-registry-api-v3-headers@docker
      - traefik.http.services.trusted-policies-registry-api-v3.loadbalancer.server.port=3000
      - traefik.http.services.trusted-policies-registry-api-v3.loadbalancer.healthcheck.path=/trusted-policies-registry/v3/health
      - traefik.http.services.trusted-policies-registry-api-v3.loadbalancer.healthcheck.headers.EBSI-Healthcheck=1
      - traefik.http.services.trusted-policies-registry-api-v3.loadbalancer.healthcheck.interval=30s
      - traefik.http.services.trusted-policies-registry-api-v3.loadbalancer.healthcheck.timeout=30s
      - traefik.http.routers.local-trusted-policies-registry-api-v3.rule=Host(`api.local`)&&PathPrefix(`/trusted-policies-registry/v3`)
      - traefik.http.routers.local-trusted-policies-registry-api-v3.service=local-trusted-policies-registry-api-v3
      - traefik.http.services.local-trusted-policies-registry-api-v3.loadbalancer.server.port=3000
      - app=trusted-policies-registry-api-v3
